name: build-binary

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "doak-cron"
          build_flags: -v
          extra_files: README.md cron.json LICENSE
