name: build-binary

on:
  release:
    types: [created]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.20
          binary_name: "doak-cron"
          build_flags: -v
          extra_files: README.md cron.json LICENSE
